# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)

# platform :android do
#   # desc "Deploy to Firebase App Distribution"
#   # lane :firebase_distribution do

#   #   # sh("wget https://github.com/appium/appium/raw/master/sample-code/apps/ApiDemos-debug.apk")

#   #   firebase_app_distribution(
#   #     apk_path: sh("pwd | tr -d '\n'").concat("/ApiDemos-debug.apk"),
#   #     # app: ENV["FIREBASE_APP_ID"],
#   #     app: "1:117827364961:android:7b39b8e6c2299325a92220",
#   #     firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
#   #     # firebase_cli_token: "1//0cM3A-ewSteDeCgYIARAAGAwSNwF-L9IrJG6fGjozDRHT6PH44EsdNAf6p1bh420iHzuclD9YRx_nCKRD3cj6DRssYt95Y27Jh8k",
#   #     groups: "",
#   #     release_notes: "Git commit: #{last_git_commit[:abbreviated_commit_hash]}",
#   #   )
#   # end

#   desc "Lane for distributing app using Firebase App Distributions"
#     lane :distribute do
#         gradle(task: "clean assembleRelease")
#         # firebase_app_distribution(
#         #     # service_credentials_file: "firebase_credentials.json",
#         #     # app: ENV['FIREBASE_APP_ID'],
#         #     app: "1:117827364961:android:7b39b8e6c2299325a92220",
#         #     firebase_cli_token: "1//0cM3A-ewSteDeCgYIARAAGAwSNwF-L9IrJG6fGjozDRHT6PH44EsdNAf6p1bh420iHzuclD9YRx_nCKRD3cj6DRssYt95Y27Jh8k",
#         #     # release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
#         #     # groups_file: "FirebaseAppDistributionConfig/groups.txt"
#         #     apk_path: "./app/build/outputs/apk/release/app-release.apk"
#         #     # android/app/build/outputs/apk/release/app-release.apk
#         # )
#         diawi(
#           token: "cFZWG3lUUzqKJgYXMT2RrxT7tlk0Ti9bgjTIblGlUp"
#         )
#     end

#   # desc "My awesome app"
#   #   lane :distribute do
#   #       # build_android_app(...)
#   #       # build_android_app is a built-in fastlane action.
#   #       firebase_app_distribution(
#   #           # app: "1:123456789:android:abcd1234",
#   #           app: "1:117827364961:android:7b39b8e6c2299325a92220",
#   #           testers: "tester1@company.com, tester2@company.com",
#   #           release_notes: "Lots of amazing new features to test out!"
#   #       )
#   #   end

#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end

default_platform :android

platform :android do

  desc "Deploy to Firebase App Distribution"
  lane :firebase_distribution do

    # build_android_app(task: "assembleRelease", project_dir: "./android")
    gradle(task: "clean assembleRelease", project_dir: "../android") # /Users/uladzislau/Desktop/react-native/spiral/android/gradlew
    # gradle(
    #   task: 'assemble',
    #   build_type: 'debug',
    #   project_dir: "./android"
    # )

    diawi(
          token: "cFZWG3lUUzqKJgYXMT2RrxT7tlk0Ti9bgjTIblGlUp"
        )
  end
end
