name: Distribute

on:
  push:
    branches: [ test ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install bundle
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane distribute
