name: Distribute

on:
  push:
    branches:
      - test
      - yabeda79-patch-2

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      
      - name: Install bundle
        run: BUNDLE_GEMFILE="react-native-lab/android/Gemfile" bundle install
          
      - name: Distribute app
        run: bundle exec fastlane distribute
